### ISSUE TITLE
unicode characters

### ISSUE THREAD

**Issue by eighteight** [kevinzweerink/ntype#2]
Please let me know how I would approach displaying non-English characters. I see that the alphabet is defined in types.js as arrays of vertex arrays. Is there a non-manual way to build the same for non-English alphabet?

Thanks.

**Comment by kevinzweerink** [comment]
Thanks for getting in touch!

All the letterforms available were designed by hand on a 28 x 24 unit grid.

I don't plan on making any more because:

a. It's a pretty labor-intensive process (all letters have to be created from scratch, communicated with as few vertices as possible, and can't have any counter-forms or curves), and then manually transcribed into type.js. 

b. This project is really more of an experiment than a practical tool.

It would be cool to make an interface that makes the letters simpler to create and add to type.js, but I don't really have plans to do that right now.

If you want, you can design some non-english characters on a 28x24 grid, add them to type.js, and submit a pull request. I'd be happy to review it!
